# -*- coding: utf-8 -*-
"""NSE_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pH2VDKJsFAlEJYd4p2l9K8hWtMb5OsbK
"""

from google.colab import userdata
import os
import pandas as pd
import requests
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json


# Retrieve the secret from Colab's Secrets Manager
try:
    google_credentials_json = userdata.get('GOOGLE_CREDENTIALS')
    # Set the environment variable for the current session
    os.environ['GOOGLE_CREDENTIALS'] = google_credentials_json
    print("GOOGLE_CREDENTIALS loaded from Colab Secrets.")
except KeyError:
    print("Error: 'GOOGLE_CREDENTIALS' not found in Colab Secrets. Please add it as instructed previously.")
    # Optionally, raise an error or exit if credentials are critical
    # raise


scope = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive"
]

creds_dict = json.loads(os.environ['GOOGLE_CREDENTIALS'])

creds = ServiceAccountCredentials.from_json_keyfile_dict(
    creds_dict,
    scope
)

client = gspread.authorize(creds)

sheet = client.open("Stock Analysis NSE Python")

worksheet = sheet.worksheet("Final List")

data = [
    ["Stock", "Price", "Volume"],
    ["RELIANCE", 2500, 100000]
]

worksheet.clear()
worksheet.update("A1", data)

print("Updated Successfully")

